### ISSUE TITLE
mEME not dAnk eNoUGh

### ISSUE THREAD

**Issue by ayylmaoooooo** [Piraato/tirimeme#1]
ey b0ss can i habe de pussi pls
My name is Tiri and i slap tits

**Comment by Piraato** [comment]
Pls add request to fix ok Teyrey?

**Comment by Piraato** [comment]
fixed

**Comment by ayylmaoooooo** [comment]
ty

**Comment by Piraato** [comment]
thanks for the info @ayylmaoooooo
